### ISSUE TITLE
不支持1.21吗

### ISSUE THREAD

**Issue by addpromax** [Skillw/Pouvoir#16]
不支持1.20.4吗

**Comment by addpromax** [comment]
[15:07:59] [Server thread/INFO]: [Pouvoir] Loading server plugin Pouvoir v1.6.6-gamma-19
[15:07:59] [Server thread/INFO]: [Pouvoir] Pou占位符 pou 注册成功! 来自: Pouvoir 1.6.6-gamma-19 By: [Glom_]
[15:07:59] [Server thread/INFO]: [Pouvoir] Pou占位符 as 注册成功! 来自: AttributeSystem 2.1.1-gamma-14 By: [Glom_]
[15:07:59] [Server thread/WARN]: com.skillw.pouvoir.taboolib.common.inject.ClassVisitException: class com.skillw.pouvoir.taboolib.module.nms.MinecraftVersion#init: VisitorGroup{priority=0, list=[AwakeFunction(lifeCycle=CONST), AwakeFunction(lifeCycle=INIT), AwakeFunction(lifeCycle=LOAD), AwakeFunction(lifeCycle=ENABLE), AwakeFunction(lifeCycle=ACTIVE), AwakeFunction(lifeCycle=DISABLE), com.skillw.pouvoir.taboolib.common.platform.event.EventBus@3ba0b85e, com.skillw.pouvoir.taboolib.common.platform.command.SimpleCommandRegister@6edf752e, com.skillw.pouvoir.taboolib.module.kether.KetherLoader@76a27bc7, com.skillw.pouvoir.taboolib.platform.compat.PlaceholderExpansion$PlaceholderRegister@73c28c67]} (LOAD)
[15:07:59] [Server thread/WARN]: 	at Pouvoir-1.6.6-gamma-19.jar//com.skillw.pouvoir.taboolib.common.inject.VisitorHandler.visitMethod(VisitorHandler.java:133)
[15:07:59] [Server thread/WARN]: 	at Pouvoir-1.6.6-gamma-19.jar//com.skillw.pouvoir.taboolib.common.inject.VisitorHandler.inject(VisitorHandler.java:101)
[15:07:59] [Server thread/WARN]: 	at Pouvoir-1.6.6-gamma-19.jar//com.skillw.pouvoir.taboolib.common.inject.VisitorHandler.injectAll(VisitorHandler.java:60)
[15:07:59] [Server thread/WARN]: 	at Pouvoir-1.6.6-gamma-19.jar//com.skillw.pouvoir.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:204)
[15:07:59] [Server thread/WARN]: 	at Pouvoir-1.6.6-gamma-19.jar//com.skillw.pouvoir.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:122)
[15:07:59] [Server thread/WARN]: 	at Pouvoir-1.6.6-gamma-19.jar//com.skillw.pouvoir.taboolib.platform.BukkitPlugin.onLoad(BukkitPlugin.java:98)
[15:07:59] [Server thread/WARN]: 	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
[15:07:59] [Server thread/WARN]: 	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
[15:07:59] [Server thread/WARN]: 	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
[15:07:59] [Server thread/WARN]: 	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
[15:07:59] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:519)
[15:07:59] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:310)
[15:07:59] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1148)
[15:07:59] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326)
[15:07:59] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[15:07:59] [Server thread/WARN]: Caused by: java.lang.IllegalStateException: Unsupported Minecraft version, plugin disabled
[15:07:59] [Server thread/WARN]: 	at Pouvoir-1.6.6-gamma-19.jar//com.skillw.pouvoir.taboolib.module.nms.MinecraftVersion.init(MinecraftVersion.kt:203)
[15:07:59] [Server thread/WARN]: 	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:731)
[15:07:59] [Server thread/WARN]: 	at Pouvoir-1.6.6-gamma-19.jar//com.skillw.pouvoir.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31)
[15:07:59] [Server thread/WARN]: 	at Pouvoir-1.6.6-gamma-19.jar//com.skillw.pouvoir.taboolib.common.platform.AwakeFunction.visit(AwakeFunction.kt:13)
[15:07:59] [Server thread/WARN]: 	at Pouvoir-1.6.6-gamma-19.jar//com.skillw.pouvoir.taboolib.common.inject.VisitorHandler.visitMethod(VisitorHandler.java:131)
[15:07:59] [Server thread/WARN]: 	... 14 more

**Comment by addpromax** [comment]
还没支持1.21吗（）
